### ISSUE TITLE
questions about the article 2018-12-12-rmpfr-tutorial: is RMPFR necessary?

### ISSUE THREAD

**Issue by Neutron3529** [mrparker909/matthew-parker#2]
I am really curious about why using a package called `RMPFR` which published this year(Published: | 2020-01-24) to CRAN rather than the normal methods.

Statisticians should have some methods to deal with statistical problem before the `RMPFR` package published.

Are there some problem that could only solved by this package?

I tried to read your tutorial but felt disappointed after reading.

A `log=T` parameter could solve nearly all the problems you mentioned in the tutorial, and provides a faster performance in time consuming.

Another problem is that why you choose `sum(dpois(0:1000,10000))` to calculate `ppois(1000,10000)`, that's really inefficient.

**Comment by mrparker909** [comment]
RMPFR has been available since well before 2020 (you are referring to the date of the most recent update to the package on CRAN). 

Log space is not always an option, however when it is an option, it is often a better solution. There is no problem that can "only be solved by this package", the RMPFR package is simply a tool allowing you to easily use arbitrary precision in your R calculations. Whether arbitrary precision is necessary or efficient for your needs is entirely dependent on what you are trying to accomplish.

I am sorry that you were disappointed after reading the tutorial, but I do appreciate the feedback.
